<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB0Ve91L\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB0Ve91L/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB0Ve91L.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB0Ve91L\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerB0Ve91L\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'B0Ve91L',
    'container.build_id' => 'ab42c15c',
    'container.build_time' => 1598821077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB0Ve91L');
