<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSnVT12x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSnVT12x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSnVT12x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSnVT12x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSnVT12x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SnVT12x',
    'container.build_id' => '9975a86e',
    'container.build_time' => 1599083983,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSnVT12x');
