<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVB4sbl6\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVB4sbl6/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVB4sbl6.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVB4sbl6\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVB4sbl6\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VB4sbl6',
    'container.build_id' => '0fc648c8',
    'container.build_time' => 1598908392,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVB4sbl6');
